# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69c828e664e0c8dc5bb662827cf0a5022cb5f7611a9d42b4526ac1f2bd38b2c0afa5173005b4016458e239098b0ab94818aea1abe28ccafd2d8d73356ba1ebcb

test:
  secret_key_base: f6470c97deff5d5f83f1ab533b132413b7447f99a17fda36f0592d6e6807d744612d95ff4a48748c663a108e6bf49e32f558246a83b45f714b85002d8a6ad6da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
